name: Electron Forge CI/CD

on:
  push:
    branches-ignore:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  # 🛠️ Build for feature branches / PRs
  build:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache Electron downloads
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
            C:\Users\runneradmin\AppData\Local\electron
          key: electron-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            electron-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Build Electron App
        run: npm run make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: electron-build-${{ github.ref_name }}-${{ matrix.os }}
          path: out/make
          retention-days: 14

  # 🧹 Cleanup after PR is merged/closed
  cleanup:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Delete artifacts for branch (Linux + Windows)
        uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            electron-build-${{ github.event.pull_request.head.ref }}-ubuntu-latest
            electron-build-${{ github.event.pull_request.head.ref }}-windows-latest

  # 🚀 Release job when pushing tags
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache Electron downloads
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/electron
            ~/.cache/electron-builder
            C:\Users\runneradmin\AppData\Local\electron
          key: electron-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            electron-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Build Electron App
        run: npm run make

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-build-${{ matrix.os }}
          path: out/make
          retention-days: 7

  # 📝 Publish GitHub Release with built artifacts
  publish-release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Linux build
        uses: actions/download-artifact@v4
        with:
          name: release-build-ubuntu-latest
          path: release/linux

      - name: Download Windows build
        uses: actions/download-artifact@v4
        with:
          name: release-build-windows-latest
          path: release/windows

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            release/linux/**
            release/windows/**
